"""create linkedin job ad

Revision ID: 7ee6530179d8
Revises: 0002
Create Date: 2026-08-18 19:48:51.635098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ee6530179d8'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_job_ad',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_cover_letters_company_jobtitle', table_name='cover_letters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cover_letters_company_jobtitle', 'cover_letters', ['company_name', 'job_title'], unique=False)
    op.drop_table('linkedin_job_ad')
    # ### end Alembic commands ###
