"""update linkedin job ad url

Revision ID: c53fd0100437
Revises: 7ee6530179d8
Create Date: 2026-08-18 20:48:39.355699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c53fd0100437'
down_revision: Union[str, Sequence[str], None] = '7ee6530179d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin_job_ad', 'url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin_job_ad', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
